// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl56Jo0zsQZPjNjTi1d2XS938cIV4-yoQ',
    appId: '1:191351733632:web:1bddb2238efd7b1f76d565',
    messagingSenderId: '191351733632',
    projectId: 'employee-notification-app',
    authDomain: 'employee-notification-app.firebaseapp.com',
    storageBucket: 'employee-notification-app.firebasestorage.app',
    measurementId: 'G-L5W03GJNHC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATCm4YZ2KkyPgV0T9KxfruG2SrvwjDxow',
    appId: '1:191351733632:android:534aa876f83ae3c976d565',
    messagingSenderId: '191351733632',
    projectId: 'employee-notification-app',
    storageBucket: 'employee-notification-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAS9zsZu7-sWkjw3RbxJLGYs2sdI1vBjwU',
    appId: '1:191351733632:ios:870c85a5ee93d5aa76d565',
    messagingSenderId: '191351733632',
    projectId: 'employee-notification-app',
    storageBucket: 'employee-notification-app.firebasestorage.app',
    iosBundleId: 'com.example.employeeNotificationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAS9zsZu7-sWkjw3RbxJLGYs2sdI1vBjwU',
    appId: '1:191351733632:ios:870c85a5ee93d5aa76d565',
    messagingSenderId: '191351733632',
    projectId: 'employee-notification-app',
    storageBucket: 'employee-notification-app.firebasestorage.app',
    iosBundleId: 'com.example.employeeNotificationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDl56Jo0zsQZPjNjTi1d2XS938cIV4-yoQ',
    appId: '1:191351733632:web:62b59b3812da03db76d565',
    messagingSenderId: '191351733632',
    projectId: 'employee-notification-app',
    authDomain: 'employee-notification-app.firebaseapp.com',
    storageBucket: 'employee-notification-app.firebasestorage.app',
    measurementId: 'G-Q5G6V468K2',
  );
}
